//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskMasterWeb.Client.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaskMasterWeb.Client.Localization.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        internal static string admin {
            get {
                return ResourceManager.GetString("admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignee.
        /// </summary>
        internal static string assignee {
            get {
                return ResourceManager.GetString("assignee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignee email.
        /// </summary>
        internal static string assignee_email {
            get {
                return ResourceManager.GetString("assignee-email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignee full name.
        /// </summary>
        internal static string assignee_full_name {
            get {
                return ResourceManager.GetString("assignee-full-name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string confirm {
            get {
                return ResourceManager.GetString("confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create project.
        /// </summary>
        internal static string create_project {
            get {
                return ResourceManager.GetString("create-project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create task.
        /// </summary>
        internal static string create_task {
            get {
                return ResourceManager.GetString("create-task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create user.
        /// </summary>
        internal static string create_user {
            get {
                return ResourceManager.GetString("create-user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string dashboard {
            get {
                return ResourceManager.GetString("dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete project.
        /// </summary>
        internal static string delete_project {
            get {
                return ResourceManager.GetString("delete-project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete project.
        /// </summary>
        internal static string delete_project_content {
            get {
                return ResourceManager.GetString("delete-project-content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete task.
        /// </summary>
        internal static string delete_task {
            get {
                return ResourceManager.GetString("delete-task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete task.
        /// </summary>
        internal static string delete_task_content {
            get {
                return ResourceManager.GetString("delete-task-content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete user.
        /// </summary>
        internal static string delete_user {
            get {
                return ResourceManager.GetString("delete-user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete user.
        /// </summary>
        internal static string delete_user_content {
            get {
                return ResourceManager.GetString("delete-user-content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string first_name {
            get {
                return ResourceManager.GetString("first-name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        internal static string full_name {
            get {
                return ResourceManager.GetString("full-name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string last_name {
            get {
                return ResourceManager.GetString("last-name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No projects found.
        /// </summary>
        internal static string no_projects_found {
            get {
                return ResourceManager.GetString("no-projects-found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tasks found.
        /// </summary>
        internal static string no_tasks_found {
            get {
                return ResourceManager.GetString("no-tasks-found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No users found.
        /// </summary>
        internal static string no_users_found {
            get {
                return ResourceManager.GetString("no-users-found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found.
        /// </summary>
        internal static string not_found {
            get {
                return ResourceManager.GetString("not-found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there&apos;s nothing at this address..
        /// </summary>
        internal static string nothing_at_address {
            get {
                return ResourceManager.GetString("nothing-at-address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of projects.
        /// </summary>
        internal static string number_of_projects {
            get {
                return ResourceManager.GetString("number-of-projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of tasks.
        /// </summary>
        internal static string number_of_tasks {
            get {
                return ResourceManager.GetString("number-of-tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        internal static string priority {
            get {
                return ResourceManager.GetString("priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string project {
            get {
                return ResourceManager.GetString("project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project assignee.
        /// </summary>
        internal static string project_assignee {
            get {
                return ResourceManager.GetString("project-assignee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project details.
        /// </summary>
        internal static string project_details {
            get {
                return ResourceManager.GetString("project-details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project name.
        /// </summary>
        internal static string project_name {
            get {
                return ResourceManager.GetString("project-name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        internal static string projects {
            get {
                return ResourceManager.GetString("projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string role {
            get {
                return ResourceManager.GetString("role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task details.
        /// </summary>
        internal static string task_details {
            get {
                return ResourceManager.GetString("task-details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        internal static string tasks {
            get {
                return ResourceManager.GetString("tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update project.
        /// </summary>
        internal static string update_project {
            get {
                return ResourceManager.GetString("update-project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update task.
        /// </summary>
        internal static string update_task {
            get {
                return ResourceManager.GetString("update-task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update user.
        /// </summary>
        internal static string update_user {
            get {
                return ResourceManager.GetString("update-user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string user {
            get {
                return ResourceManager.GetString("user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User details.
        /// </summary>
        internal static string user_details {
            get {
                return ResourceManager.GetString("user-details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string users {
            get {
                return ResourceManager.GetString("users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
    }
}
