//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskMasterWeb.Client.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_hr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_hr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaskMasterWeb.Client.Localization.Resource.hr", typeof(Resource_hr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADMIN.
        /// </summary>
        internal static string admin {
            get {
                return ResourceManager.GetString("admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnik.
        /// </summary>
        internal static string assignee {
            get {
                return ResourceManager.GetString("assignee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email korisnika.
        /// </summary>
        internal static string assignee_email {
            get {
                return ResourceManager.GetString("assignee-email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime korisnika.
        /// </summary>
        internal static string assignee_full_name {
            get {
                return ResourceManager.GetString("assignee-full-name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaostatak.
        /// </summary>
        internal static string backlog {
            get {
                return ResourceManager.GetString("backlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odustani.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zatvori.
        /// </summary>
        internal static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Završeno.
        /// </summary>
        internal static string completed {
            get {
                return ResourceManager.GetString("completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrdi.
        /// </summary>
        internal static string confirm {
            get {
                return ResourceManager.GetString("confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kreiraj projekt.
        /// </summary>
        internal static string create_project {
            get {
                return ResourceManager.GetString("create-project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izradi izvješće.
        /// </summary>
        internal static string create_report {
            get {
                return ResourceManager.GetString("create-report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kreiraj zadatak.
        /// </summary>
        internal static string create_task {
            get {
                return ResourceManager.GetString("create-task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kreiraj korisnika.
        /// </summary>
        internal static string create_user {
            get {
                return ResourceManager.GetString("create-user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontrolna ploča.
        /// </summary>
        internal static string dashboard {
            get {
                return ResourceManager.GetString("dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obriši projekt.
        /// </summary>
        internal static string delete_project {
            get {
                return ResourceManager.GetString("delete-project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeste li sigurni da želite obrisati projekt.
        /// </summary>
        internal static string delete_project_content {
            get {
                return ResourceManager.GetString("delete-project-content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izbriši izvješće.
        /// </summary>
        internal static string delete_report {
            get {
                return ResourceManager.GetString("delete-report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeste li sigurni da želite izbrisati izvješće koje je generirano.
        /// </summary>
        internal static string delete_report_content {
            get {
                return ResourceManager.GetString("delete-report-content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obriši zadatak.
        /// </summary>
        internal static string delete_task {
            get {
                return ResourceManager.GetString("delete-task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeste li sigurni da želite obrisati zadatak.
        /// </summary>
        internal static string delete_task_content {
            get {
                return ResourceManager.GetString("delete-task-content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obriši korisnika.
        /// </summary>
        internal static string delete_user {
            get {
                return ResourceManager.GetString("delete-user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeste li sigurni da želite obrisati korisnika.
        /// </summary>
        internal static string delete_user_content {
            get {
                return ResourceManager.GetString("delete-user-content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis.
        /// </summary>
        internal static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pogreška prilikom izrade projekta.
        /// </summary>
        internal static string error_creating_project {
            get {
                return ResourceManager.GetString("error-creating-project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pogreška prilikom izrade izvješća.
        /// </summary>
        internal static string error_creating_report {
            get {
                return ResourceManager.GetString("error-creating-report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pogreška prilikom izrade zadatka.
        /// </summary>
        internal static string error_creating_task {
            get {
                return ResourceManager.GetString("error-creating-task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pogreška prilikom izrade korisnika.
        /// </summary>
        internal static string error_creating_user {
            get {
                return ResourceManager.GetString("error-creating-user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pogreška prilikom brisanja projekta.
        /// </summary>
        internal static string error_deleting_project {
            get {
                return ResourceManager.GetString("error-deleting-project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pogreška prilikom brisanja izvješća.
        /// </summary>
        internal static string error_deleting_report {
            get {
                return ResourceManager.GetString("error-deleting-report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pogreška prilikom brisanja zadatka.
        /// </summary>
        internal static string error_deleting_task {
            get {
                return ResourceManager.GetString("error-deleting-task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pogreška prilikom brisanja korisnika.
        /// </summary>
        internal static string error_deleting_user {
            get {
                return ResourceManager.GetString("error-deleting-user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pogreška prilikom učitavanja projekata.
        /// </summary>
        internal static string error_loading_projects {
            get {
                return ResourceManager.GetString("error-loading-projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pogreška prilikom učitavanja projekata i zadataka.
        /// </summary>
        internal static string error_loading_projects_and_tasks {
            get {
                return ResourceManager.GetString("error-loading-projects-and-tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pogreška prilikom učitavanja projekata i korisnika.
        /// </summary>
        internal static string error_loading_projects_and_users {
            get {
                return ResourceManager.GetString("error-loading-projects-and-users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pogreška prilikom učitavanja izvješća.
        /// </summary>
        internal static string error_loading_reports {
            get {
                return ResourceManager.GetString("error-loading-reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pogreška prilikom učitavanja zadataka.
        /// </summary>
        internal static string error_loading_tasks {
            get {
                return ResourceManager.GetString("error-loading-tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pogreška prilikom učitavanja korisnika.
        /// </summary>
        internal static string error_loading_users {
            get {
                return ResourceManager.GetString("error-loading-users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pogreška prilikom ažuriranja projekta.
        /// </summary>
        internal static string error_updating_project {
            get {
                return ResourceManager.GetString("error-updating-project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pogreška prilikom ažuriranja zadatka.
        /// </summary>
        internal static string error_updating_task {
            get {
                return ResourceManager.GetString("error-updating-task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pogreška prilikom ažuriranja statusa zadatka.
        /// </summary>
        internal static string error_updating_task_status {
            get {
                return ResourceManager.GetString("error-updating-task-status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pogreška prilikom ažuriranja korisnika.
        /// </summary>
        internal static string error_updating_user {
            get {
                return ResourceManager.GetString("error-updating-user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime.
        /// </summary>
        internal static string first_name {
            get {
                return ResourceManager.GetString("first-name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puno ime.
        /// </summary>
        internal static string full_name {
            get {
                return ResourceManager.GetString("full-name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generirano.
        /// </summary>
        internal static string generated_at {
            get {
                return ResourceManager.GetString("generated-at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visoki.
        /// </summary>
        internal static string high {
            get {
                return ResourceManager.GetString("high", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U nastajanju.
        /// </summary>
        internal static string in_progress {
            get {
                return ResourceManager.GetString("in-progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nevažeće vjerodajnice.
        /// </summary>
        internal static string invalid_credentials {
            get {
                return ResourceManager.GetString("invalid-credentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime.
        /// </summary>
        internal static string last_name {
            get {
                return ResourceManager.GetString("last-name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prijavi se.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odjavi se.
        /// </summary>
        internal static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nizak.
        /// </summary>
        internal static string low {
            get {
                return ResourceManager.GetString("low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Srednji.
        /// </summary>
        internal static string medium {
            get {
                return ResourceManager.GetString("medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projekti nisu pronađeni.
        /// </summary>
        internal static string no_projects_found {
            get {
                return ResourceManager.GetString("no-projects-found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izvješća nisu pronađena
        ///.
        /// </summary>
        internal static string no_reports_found {
            get {
                return ResourceManager.GetString("no-reports-found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadaci nisu pronađeni.
        /// </summary>
        internal static string no_tasks_found {
            get {
                return ResourceManager.GetString("no-tasks-found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnici nisu pronađeni.
        /// </summary>
        internal static string no_users_found {
            get {
                return ResourceManager.GetString("no-users-found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nije pronađeno.
        /// </summary>
        internal static string not_found {
            get {
                return ResourceManager.GetString("not-found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nažalost, na ovoj adresi nema ničega..
        /// </summary>
        internal static string nothing_at_address {
            get {
                return ResourceManager.GetString("nothing-at-address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj projekata.
        /// </summary>
        internal static string number_of_projects {
            get {
                return ResourceManager.GetString("number-of-projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj zadataka.
        /// </summary>
        internal static string number_of_tasks {
            get {
                return ResourceManager.GetString("number-of-tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prioritet.
        /// </summary>
        internal static string priority {
            get {
                return ResourceManager.GetString("priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projekt.
        /// </summary>
        internal static string project {
            get {
                return ResourceManager.GetString("project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnik projekta.
        /// </summary>
        internal static string project_assignee {
            get {
                return ResourceManager.GetString("project-assignee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalji projekta.
        /// </summary>
        internal static string project_details {
            get {
                return ResourceManager.GetString("project-details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime projekta.
        /// </summary>
        internal static string project_name {
            get {
                return ResourceManager.GetString("project-name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projekti.
        /// </summary>
        internal static string projects {
            get {
                return ResourceManager.GetString("projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izvješće je uspješno kreirano.
        /// </summary>
        internal static string report_created {
            get {
                return ResourceManager.GetString("report-created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izvještaji.
        /// </summary>
        internal static string reports {
            get {
                return ResourceManager.GetString("reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uloga.
        /// </summary>
        internal static string role {
            get {
                return ResourceManager.GetString("role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalji zadatka.
        /// </summary>
        internal static string task_details {
            get {
                return ResourceManager.GetString("task-details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadaci.
        /// </summary>
        internal static string tasks {
            get {
                return ResourceManager.GetString("tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavljeni zadaci.
        /// </summary>
        internal static string tasks_completed {
            get {
                return ResourceManager.GetString("tasks-completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadaci u zaostatku.
        /// </summary>
        internal static string tasks_in_backlog {
            get {
                return ResourceManager.GetString("tasks-in-backlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadaci u tijeku.
        /// </summary>
        internal static string tasks_in_progress {
            get {
                return ResourceManager.GetString("tasks-in-progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukupno zadataka.
        /// </summary>
        internal static string total_tasks {
            get {
                return ResourceManager.GetString("total-tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ažuriraj projekt.
        /// </summary>
        internal static string update_project {
            get {
                return ResourceManager.GetString("update-project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ažuriraj zadatak.
        /// </summary>
        internal static string update_task {
            get {
                return ResourceManager.GetString("update-task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ažuriraj korisnika.
        /// </summary>
        internal static string update_user {
            get {
                return ResourceManager.GetString("update-user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USER.
        /// </summary>
        internal static string user {
            get {
                return ResourceManager.GetString("user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalji korisnika.
        /// </summary>
        internal static string user_details {
            get {
                return ResourceManager.GetString("user-details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnici.
        /// </summary>
        internal static string users {
            get {
                return ResourceManager.GetString("users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dobrodošli.
        /// </summary>
        internal static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
    }
}
