//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskMasterWeb.Client.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_it {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_it() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaskMasterWeb.Client.Localization.Resource.it", typeof(Resource_it).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADMIN.
        /// </summary>
        internal static string admin {
            get {
                return ResourceManager.GetString("admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assegnatario.
        /// </summary>
        internal static string assignee {
            get {
                return ResourceManager.GetString("assignee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail dell&apos;assegnatario.
        /// </summary>
        internal static string assignee_email {
            get {
                return ResourceManager.GetString("assignee-email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome completo dell&apos;assegnatario.
        /// </summary>
        internal static string assignee_full_name {
            get {
                return ResourceManager.GetString("assignee-full-name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arretrato.
        /// </summary>
        internal static string backlog {
            get {
                return ResourceManager.GetString("backlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annulla.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vicino.
        /// </summary>
        internal static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completato.
        /// </summary>
        internal static string completed {
            get {
                return ResourceManager.GetString("completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confermare.
        /// </summary>
        internal static string confirm {
            get {
                return ResourceManager.GetString("confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crea progetto.
        /// </summary>
        internal static string create_project {
            get {
                return ResourceManager.GetString("create-project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crea rapporto.
        /// </summary>
        internal static string create_report {
            get {
                return ResourceManager.GetString("create-report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crea attività.
        /// </summary>
        internal static string create_task {
            get {
                return ResourceManager.GetString("create-task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creare un utente.
        /// </summary>
        internal static string create_user {
            get {
                return ResourceManager.GetString("create-user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pannello di controllo.
        /// </summary>
        internal static string dashboard {
            get {
                return ResourceManager.GetString("dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elimina progetto.
        /// </summary>
        internal static string delete_project {
            get {
                return ResourceManager.GetString("delete-project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sei sicuro di voler eliminare il progetto.
        /// </summary>
        internal static string delete_project_content {
            get {
                return ResourceManager.GetString("delete-project-content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elimina rapporto.
        /// </summary>
        internal static string delete_report {
            get {
                return ResourceManager.GetString("delete-report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sei sicuro di voler eliminare il report generato in.
        /// </summary>
        internal static string delete_report_content {
            get {
                return ResourceManager.GetString("delete-report-content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elimina attività.
        /// </summary>
        internal static string delete_task {
            get {
                return ResourceManager.GetString("delete-task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sei sicuro di voler eliminare l&apos;attività.
        /// </summary>
        internal static string delete_task_content {
            get {
                return ResourceManager.GetString("delete-task-content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elimina utente.
        /// </summary>
        internal static string delete_user {
            get {
                return ResourceManager.GetString("delete-user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sei sicuro di voler eliminare l&apos;utente.
        /// </summary>
        internal static string delete_user_content {
            get {
                return ResourceManager.GetString("delete-user-content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrizione.
        /// </summary>
        internal static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elimina rapporto.
        /// </summary>
        internal static string error_creating_project {
            get {
                return ResourceManager.GetString("error-creating-project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore durante la creazione del rapporto.
        /// </summary>
        internal static string error_creating_report {
            get {
                return ResourceManager.GetString("error-creating-report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore durante la creazione dell&apos;attività.
        /// </summary>
        internal static string error_creating_task {
            get {
                return ResourceManager.GetString("error-creating-task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore durante la creazione dell&apos;utente.
        /// </summary>
        internal static string error_creating_user {
            get {
                return ResourceManager.GetString("error-creating-user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore durante l&apos;eliminazione del progetto.
        /// </summary>
        internal static string error_deleting_project {
            get {
                return ResourceManager.GetString("error-deleting-project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore durante l&apos;eliminazione del rapporto.
        /// </summary>
        internal static string error_deleting_report {
            get {
                return ResourceManager.GetString("error-deleting-report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore durante l&apos;eliminazione dell&apos;attività.
        /// </summary>
        internal static string error_deleting_task {
            get {
                return ResourceManager.GetString("error-deleting-task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore durante l&apos;eliminazione dell&apos;utente.
        /// </summary>
        internal static string error_deleting_user {
            get {
                return ResourceManager.GetString("error-deleting-user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore durante il caricamento dei progetti.
        /// </summary>
        internal static string error_loading_projects {
            get {
                return ResourceManager.GetString("error-loading-projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore durante il caricamento di progetti e attività.
        /// </summary>
        internal static string error_loading_projects_and_tasks {
            get {
                return ResourceManager.GetString("error-loading-projects-and-tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore durante il caricamento di progetti e utenti.
        /// </summary>
        internal static string error_loading_projects_and_users {
            get {
                return ResourceManager.GetString("error-loading-projects-and-users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore durante il caricamento dei report.
        /// </summary>
        internal static string error_loading_reports {
            get {
                return ResourceManager.GetString("error-loading-reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore durante il caricamento delle attività.
        /// </summary>
        internal static string error_loading_tasks {
            get {
                return ResourceManager.GetString("error-loading-tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore durante il caricamento degli utenti.
        /// </summary>
        internal static string error_loading_users {
            get {
                return ResourceManager.GetString("error-loading-users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore durante il caricamento degli utenti.
        /// </summary>
        internal static string error_updating_project {
            get {
                return ResourceManager.GetString("error-updating-project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore durante l&apos;aggiornamento dell&apos;attività.
        /// </summary>
        internal static string error_updating_task {
            get {
                return ResourceManager.GetString("error-updating-task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore durante l&apos;aggiornamento dello stato dell&apos;attività.
        /// </summary>
        internal static string error_updating_task_status {
            get {
                return ResourceManager.GetString("error-updating-task-status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore durante l&apos;aggiornamento dell&apos;utente.
        /// </summary>
        internal static string error_updating_user {
            get {
                return ResourceManager.GetString("error-updating-user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome di battesimo.
        /// </summary>
        internal static string first_name {
            get {
                return ResourceManager.GetString("first-name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome e cognome.
        /// </summary>
        internal static string full_name {
            get {
                return ResourceManager.GetString("full-name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generato a.
        /// </summary>
        internal static string generated_at {
            get {
                return ResourceManager.GetString("generated-at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alta.
        /// </summary>
        internal static string high {
            get {
                return ResourceManager.GetString("high", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In corso.
        /// </summary>
        internal static string in_progress {
            get {
                return ResourceManager.GetString("in-progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credenziali non valide.
        /// </summary>
        internal static string invalid_credentials {
            get {
                return ResourceManager.GetString("invalid-credentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cognome.
        /// </summary>
        internal static string last_name {
            get {
                return ResourceManager.GetString("last-name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnettersi.
        /// </summary>
        internal static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bassa.
        /// </summary>
        internal static string low {
            get {
                return ResourceManager.GetString("low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media.
        /// </summary>
        internal static string medium {
            get {
                return ResourceManager.GetString("medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nessun progetto trovato.
        /// </summary>
        internal static string no_projects_found {
            get {
                return ResourceManager.GetString("no-projects-found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nessun rapporto trovato.
        /// </summary>
        internal static string no_reports_found {
            get {
                return ResourceManager.GetString("no-reports-found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nessuna attività trovata.
        /// </summary>
        internal static string no_tasks_found {
            get {
                return ResourceManager.GetString("no-tasks-found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nessun utente trovato.
        /// </summary>
        internal static string no_users_found {
            get {
                return ResourceManager.GetString("no-users-found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non trovato.
        /// </summary>
        internal static string not_found {
            get {
                return ResourceManager.GetString("not-found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mi dispiace, non c&apos;è niente a questo indirizzo..
        /// </summary>
        internal static string nothing_at_address {
            get {
                return ResourceManager.GetString("nothing-at-address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero di progetti.
        /// </summary>
        internal static string number_of_projects {
            get {
                return ResourceManager.GetString("number-of-projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero di compiti.
        /// </summary>
        internal static string number_of_tasks {
            get {
                return ResourceManager.GetString("number-of-tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parola d&apos;ordine.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priorità.
        /// </summary>
        internal static string priority {
            get {
                return ResourceManager.GetString("priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progetto.
        /// </summary>
        internal static string project {
            get {
                return ResourceManager.GetString("project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assegnatario del progetto.
        /// </summary>
        internal static string project_assignee {
            get {
                return ResourceManager.GetString("project-assignee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dettagli del progetto.
        /// </summary>
        internal static string project_details {
            get {
                return ResourceManager.GetString("project-details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome del progetto.
        /// </summary>
        internal static string project_name {
            get {
                return ResourceManager.GetString("project-name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progetti.
        /// </summary>
        internal static string projects {
            get {
                return ResourceManager.GetString("projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapporto creato con successo.
        /// </summary>
        internal static string report_created {
            get {
                return ResourceManager.GetString("report-created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapporti.
        /// </summary>
        internal static string reports {
            get {
                return ResourceManager.GetString("reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruolo.
        /// </summary>
        internal static string role {
            get {
                return ResourceManager.GetString("role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stato.
        /// </summary>
        internal static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dettagli dell&apos;attività.
        /// </summary>
        internal static string task_details {
            get {
                return ResourceManager.GetString("task-details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiti.
        /// </summary>
        internal static string tasks {
            get {
                return ResourceManager.GetString("tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attività completate.
        /// </summary>
        internal static string tasks_completed {
            get {
                return ResourceManager.GetString("tasks-completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiti in arretrato.
        /// </summary>
        internal static string tasks_in_backlog {
            get {
                return ResourceManager.GetString("tasks-in-backlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiti in corso.
        /// </summary>
        internal static string tasks_in_progress {
            get {
                return ResourceManager.GetString("tasks-in-progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiti totali.
        /// </summary>
        internal static string total_tasks {
            get {
                return ResourceManager.GetString("total-tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiorna progetto.
        /// </summary>
        internal static string update_project {
            get {
                return ResourceManager.GetString("update-project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiorna progetto.
        /// </summary>
        internal static string update_task {
            get {
                return ResourceManager.GetString("update-task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiorna utente.
        /// </summary>
        internal static string update_user {
            get {
                return ResourceManager.GetString("update-user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USER.
        /// </summary>
        internal static string user {
            get {
                return ResourceManager.GetString("user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dettagli dell&apos;utente.
        /// </summary>
        internal static string user_details {
            get {
                return ResourceManager.GetString("user-details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utenti.
        /// </summary>
        internal static string users {
            get {
                return ResourceManager.GetString("users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benvenuto.
        /// </summary>
        internal static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
    }
}
